apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clock-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clock-api
  template:
    metadata:
      labels:
        app: clock-api
        svc: clock-api
        env: prod
    spec:
      imagePullSecrets:
        - name: algo-cred
      containers:
        - name: clock-go
          image: docker.algo.fit/ec2ainun/usvc-time:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 2000
          env:
            - name: SERVICE_NAME
              value: "clock-svc-golang"
            - name: PORT
              value: "2000"
